import type { FieldDefinition, ObjectDefinition, RelationshipDefinition } from "./types.js";

type FieldOptions = Partial<Omit<FieldDefinition, "name" | "type">>;

const field = (
  name: string,
  type: FieldDefinition["type"],
  options: FieldOptions = {},
): FieldDefinition => ({
  name,
  type,
  required: options.required ?? false,
  unique: options.unique ?? false,
  maxLength: options.maxLength ?? null,
  lookup: options.lookup ?? null,
  validation: options.validation ?? null,
  classification: options.classification ?? "internal",
  aiReadable: options.aiReadable ?? false,
  aiWritable: options.aiWritable ?? false,
  searchable: options.searchable ?? false,
  apiExposed: options.apiExposed ?? false,
});

const relationship = (
  name: string,
  target: string,
  cardinality: RelationshipDefinition["cardinality"],
  cascade = false,
): RelationshipDefinition => ({ name, target, cardinality, cascade });

const currencies = { allowedValues: ["USD", "ZWG"] } as const;
const countryCode = { pattern: "^[A-Z]{2}$" } as const;
const email = { pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$" } as const;
const httpsUrl = { pattern: "^https://" } as const;
const webUrl = { pattern: "^https?://" } as const;
const logoUrl = { pattern: "^(?:https://|data:image/(?:png|jpeg);base64,)" } as const;
const money = { pattern: "^-?\\d{1,12}(?:\\.\\d{1,2})?$" } as const;
const nonNegativeMoney = {
  pattern: "^\\d{1,12}(?:\\.\\d{1,2})?$",
  minimum: 0,
} as const;
const exchangeRate = { pattern: "^\\d{1,12}(?:\\.\\d{1,6})?$", minimum: 0 } as const;

const contactFields = (role: "customer" | "supplier"): FieldDefinition[] => [
  field("id", "uuid", { unique: true, apiExposed: true }),
  field("tenantId", "uuid", { lookup: "Company" }),
  field("type", "string", {
    validation: { allowedValues: ["INDIVIDUAL", "COMPANY"] },
    aiReadable: true,
    apiExposed: true,
  }),
  field("name", "string", {
    required: true,
    maxLength: 200,
    validation: { minLength: 1 },
    classification: "confidential",
    aiReadable: true,
    searchable: true,
    apiExposed: true,
  }),
  field("email", "string", {
    maxLength: 254,
    validation: email,
    classification: "restricted",
    apiExposed: true,
  }),
  field("phone", "string", { maxLength: 50, classification: "restricted", apiExposed: true }),
  field("address", "string", { maxLength: 500, classification: "restricted", apiExposed: true }),
  field("addressLine1", "string", { maxLength: 200, classification: "restricted", apiExposed: true }),
  field("addressLine2", "string", { maxLength: 200, classification: "restricted", apiExposed: true }),
  field("city", "string", {
    maxLength: 100,
    classification: "confidential",
    aiReadable: true,
    apiExposed: true,
  }),
  field("region", "string", {
    maxLength: 100,
    classification: "confidential",
    aiReadable: true,
    apiExposed: true,
  }),
  field("postalCode", "string", { maxLength: 30, classification: "restricted", apiExposed: true }),
  field("countryCode", "string", {
    maxLength: 2,
    validation: countryCode,
    classification: "confidential",
    aiReadable: true,
    apiExposed: true,
  }),
  field("website", "string", {
    maxLength: 500,
    validation: webUrl,
    classification: "confidential",
    aiReadable: true,
    apiExposed: true,
  }),
  field("industry", "string", {
    maxLength: 100,
    classification: "confidential",
    aiReadable: true,
    searchable: true,
    apiExposed: true,
  }),
  field("registrationNumber", "string", { maxLength: 100, classification: "restricted", apiExposed: true }),
  field("notes", "string", { maxLength: 5_000, classification: "restricted", apiExposed: true }),
  field("taxNumber", "string", { maxLength: 100, classification: "restricted", apiExposed: true }),
  field("tags", "string[]", {
    maxLength: 50,
    validation: { maxItems: 50, uniqueItems: true },
    classification: "confidential",
    aiReadable: true,
    searchable: true,
    apiExposed: true,
  }),
  field("isCustomer", "boolean", { apiExposed: true }),
  field("isVendor", "boolean", { apiExposed: role === "customer" }),
  field("supplierCode", "string", {
    unique: true,
    maxLength: 50,
    validation: { pattern: "^[A-Za-z0-9][A-Za-z0-9._/-]*$" },
    aiReadable: role === "supplier",
    searchable: role === "supplier",
    apiExposed: role === "supplier",
  }),
  field("supplierCurrency", "string", {
    validation: currencies,
    aiReadable: role === "supplier",
    apiExposed: role === "supplier",
  }),
  field("supplierPaymentTermsDays", "integer", {
    validation: { minimum: 0, maximum: 3_650 },
    classification: "confidential",
    aiReadable: role === "supplier",
    apiExposed: role === "supplier",
  }),
  field("supplierLeadTimeDays", "integer", {
    validation: { minimum: 0, maximum: 3_650 },
    classification: "confidential",
    aiReadable: role === "supplier",
    apiExposed: role === "supplier",
  }),
  field("ownerUserId", "uuid", { lookup: "User" }),
  field("deletedAt", "datetime"),
  field("deletedBy", "uuid", { lookup: "User" }),
  field("createdAt", "datetime", { apiExposed: true }),
];

export const CANONICAL_OBJECT_DEFINITIONS: readonly ObjectDefinition[] = [
  {
    name: "Company",
    parent: null,
    domain: "platform",
    searchable: false,
    aiVisible: true,
    auditEnabled: true,
    lifecycle: ["TRIAL", "ACTIVE", "PAST_DUE", "SUSPENDED", "CLOSED"],
    relationships: [
      relationship("customers", "Customer", "one-to-many"),
      relationship("suppliers", "Supplier", "one-to-many"),
      relationship("invoices", "Invoice", "one-to-many"),
      relationship("payments", "Payment", "one-to-many"),
      relationship("products", "Product", "one-to-many"),
      relationship("employees", "Employee", "one-to-many"),
      relationship("users", "User", "one-to-many"),
    ],
    fields: [
      field("id", "uuid", { unique: true, apiExposed: true }),
      field("companyName", "string", {
        required: true,
        maxLength: 160,
        validation: { minLength: 2 },
        aiReadable: true,
        apiExposed: true,
      }),
      field("subdomain", "string", {
        required: true,
        unique: true,
        maxLength: 31,
        validation: { pattern: "^[a-z0-9][a-z0-9-]{2,30}$" },
        apiExposed: true,
      }),
      field("customDomain", "string", { maxLength: 253, classification: "confidential", apiExposed: true }),
      field("logoUrl", "string", { maxLength: 700_000, validation: logoUrl, apiExposed: true }),
      field("brandPrimaryColor", "string", { maxLength: 7, validation: { pattern: "^#[0-9a-fA-F]{6}$" }, apiExposed: true }),
      field("brandSecondaryColor", "string", { maxLength: 7, validation: { pattern: "^#[0-9a-fA-F]{6}$" }, apiExposed: true }),
      field("baseCurrency", "string", { required: true, validation: currencies, aiReadable: true, apiExposed: true }),
      field("countryCode", "string", { maxLength: 2, validation: countryCode, aiReadable: true, apiExposed: true }),
      field("status", "string", {
        validation: { allowedValues: ["TRIAL", "ACTIVE", "PAST_DUE", "SUSPENDED", "CLOSED"] },
        aiReadable: true,
        apiExposed: true,
      }),
      field("trialEndsAt", "datetime", { apiExposed: true }),
      field("taxNumber", "string", { maxLength: 100, classification: "restricted", apiExposed: true }),
      field("vatNumber", "string", { maxLength: 100, classification: "restricted", apiExposed: true }),
      field("registrationNumber", "string", { maxLength: 100, classification: "confidential", apiExposed: true }),
      field("physicalAddress", "string", { maxLength: 500, classification: "restricted", apiExposed: true }),
      field("invoicePaymentTerms", "string", { maxLength: 1_000, classification: "confidential", aiReadable: true, apiExposed: true }),
      field("invoiceBankName", "string", { maxLength: 160, classification: "restricted", apiExposed: true }),
      field("invoiceBankAccountName", "string", { maxLength: 160, classification: "restricted", apiExposed: true }),
      field("invoiceBankAccountNumber", "string", { maxLength: 100, classification: "restricted", apiExposed: true }),
      field("invoiceBankBranch", "string", { maxLength: 160, classification: "restricted", apiExposed: true }),
      field("invoiceBankSwiftCode", "string", { maxLength: 50, classification: "restricted", apiExposed: true }),
      field("invoiceBankCurrency", "string", { validation: currencies, classification: "confidential", apiExposed: true }),
      field("showVatNumberOnInvoices", "boolean", { apiExposed: true }),
      field("signOutDestination", "string", {
        validation: { allowedValues: ["PUBLIC_HOME", "HOLDING_PAGE"] },
        apiExposed: true,
      }),
      field("idleSignOutEnabled", "boolean", { apiExposed: true }),
      field("idleSignOutMinutes", "integer", { validation: { minimum: 5, maximum: 480 }, apiExposed: true }),
      field("holdingPageHeading", "string", { maxLength: 100, apiExposed: true }),
      field("holdingPageMessage", "string", { maxLength: 500, apiExposed: true }),
      field("holdingOfferTitle", "string", { maxLength: 100, apiExposed: true }),
      field("holdingOfferBody", "string", { maxLength: 500, apiExposed: true }),
      field("holdingOfferCtaLabel", "string", { maxLength: 50, apiExposed: true }),
      field("holdingOfferCtaUrl", "string", { maxLength: 2_048, validation: httpsUrl, apiExposed: true }),
      field("createdAt", "datetime", { apiExposed: true }),
    ],
  },
  {
    name: "Customer",
    parent: "Company",
    domain: "crm",
    searchable: true,
    aiVisible: true,
    auditEnabled: true,
    lifecycle: ["ACTIVE", "DELETED"],
    relationships: [
      relationship("company", "Company", "many-to-one"),
      relationship("invoices", "Invoice", "one-to-many"),
      relationship("owner", "User", "many-to-one"),
      relationship("deletedBy", "User", "many-to-one"),
    ],
    fields: contactFields("customer"),
  },
  {
    name: "Supplier",
    parent: "Company",
    domain: "procurement",
    searchable: true,
    aiVisible: true,
    auditEnabled: true,
    lifecycle: ["ACTIVE", "DELETED"],
    relationships: [
      relationship("company", "Company", "many-to-one"),
      relationship("owner", "User", "many-to-one"),
      relationship("deletedBy", "User", "many-to-one"),
    ],
    fields: contactFields("supplier"),
  },
  {
    name: "Invoice",
    parent: "Company",
    domain: "finance",
    searchable: true,
    aiVisible: true,
    auditEnabled: true,
    lifecycle: ["DRAFT", "ISSUED", "PARTIAL", "PAID", "VOID"],
    relationships: [
      relationship("company", "Company", "many-to-one"),
      relationship("customer", "Customer", "many-to-one"),
      relationship("payments", "Payment", "one-to-many"),
      relationship("createdBy", "User", "many-to-one"),
      relationship("products", "Product", "many-to-many"),
    ],
    fields: [
      field("id", "uuid", { unique: true, apiExposed: true }),
      field("tenantId", "uuid", { lookup: "Company" }),
      field("contactId", "uuid", { required: true, lookup: "Customer", apiExposed: true }),
      field("number", "string", { unique: true, maxLength: 64, aiReadable: true, searchable: true, apiExposed: true }),
      field("currency", "string", { required: true, validation: currencies, aiReadable: true, apiExposed: true }),
      field("rateToBase", "decimal", { validation: exchangeRate, classification: "confidential", aiReadable: true, apiExposed: true }),
      field("status", "string", {
        validation: { allowedValues: ["DRAFT", "ISSUED", "PARTIAL", "PAID", "VOID"] },
        aiReadable: true,
        searchable: true,
        apiExposed: true,
      }),
      field("issueDate", "datetime", { aiReadable: true, apiExposed: true }),
      field("dueDate", "datetime", { aiReadable: true, apiExposed: true }),
      field("taxJurisdiction", "string", { maxLength: 2, validation: countryCode, classification: "confidential", aiReadable: true, apiExposed: true }),
      field("taxDate", "date", { classification: "confidential", aiReadable: true, apiExposed: true }),
      field("taxTreatment", "string", {
        validation: { allowedValues: ["standard", "zero-rated", "exempt", "mixed"] },
        classification: "confidential",
        aiReadable: true,
        apiExposed: true,
      }),
      field("subtotal", "decimal", { validation: nonNegativeMoney, classification: "confidential", aiReadable: true, apiExposed: true }),
      field("taxTotal", "decimal", { validation: nonNegativeMoney, classification: "confidential", aiReadable: true, apiExposed: true }),
      field("total", "decimal", { validation: nonNegativeMoney, classification: "confidential", aiReadable: true, apiExposed: true }),
      field("amountPaid", "decimal", { validation: nonNegativeMoney, classification: "confidential", aiReadable: true, apiExposed: true }),
      field("notes", "string", { maxLength: 5_000, classification: "restricted", apiExposed: true }),
      field("createdBy", "uuid", { lookup: "User" }),
      field("createdAt", "datetime", { apiExposed: true }),
    ],
  },
  {
    name: "Payment",
    parent: "Company",
    domain: "finance",
    searchable: false,
    aiVisible: true,
    auditEnabled: true,
    lifecycle: ["POSTED"],
    relationships: [
      relationship("company", "Company", "many-to-one"),
      relationship("invoice", "Invoice", "many-to-one"),
      relationship("createdBy", "User", "many-to-one"),
    ],
    fields: [
      field("id", "uuid", { unique: true, apiExposed: true }),
      field("tenantId", "uuid", { lookup: "Company" }),
      field("invoiceId", "uuid", { required: true, lookup: "Invoice", apiExposed: true }),
      field("bankAccountId", "uuid", { classification: "confidential", apiExposed: true }),
      field("amount", "decimal", { required: true, validation: nonNegativeMoney, classification: "confidential", aiReadable: true, apiExposed: true }),
      field("currency", "string", { required: true, validation: currencies, aiReadable: true, apiExposed: true }),
      field("date", "datetime", { required: true, aiReadable: true, apiExposed: true }),
      field("reference", "string", { maxLength: 500, classification: "restricted", apiExposed: true }),
      field("idempotencyKey", "string", { unique: true, maxLength: 120 }),
      field("idempotencyFingerprint", "string", { maxLength: 128, classification: "restricted" }),
      field("createdBy", "uuid", { lookup: "User" }),
      field("createdAt", "datetime", { apiExposed: true }),
    ],
  },
  {
    name: "Product",
    parent: "Company",
    domain: "inventory",
    searchable: true,
    aiVisible: true,
    auditEnabled: true,
    lifecycle: ["ACTIVE", "INACTIVE"],
    relationships: [
      relationship("company", "Company", "many-to-one"),
      relationship("invoices", "Invoice", "many-to-many"),
    ],
    fields: [
      field("id", "uuid", { unique: true, apiExposed: true }),
      field("tenantId", "uuid", { lookup: "Company" }),
      field("sku", "string", {
        required: true,
        unique: true,
        maxLength: 64,
        validation: { minLength: 1 },
        aiReadable: true,
        searchable: true,
        apiExposed: true,
      }),
      field("name", "string", {
        required: true,
        maxLength: 200,
        validation: { minLength: 1 },
        aiReadable: true,
        searchable: true,
        apiExposed: true,
      }),
      field("description", "string", { maxLength: 5_000, aiReadable: true, searchable: true, apiExposed: true }),
      field("unitOfMeasure", "string", { maxLength: 40, aiReadable: true, apiExposed: true }),
      field("costPrice", "decimal", { validation: nonNegativeMoney, classification: "restricted", apiExposed: true }),
      field("salePrice", "decimal", { validation: nonNegativeMoney, classification: "confidential", aiReadable: true, apiExposed: true }),
      field("currency", "string", { validation: currencies, aiReadable: true, apiExposed: true }),
      field("taxRate", "decimal", { validation: { ...money, minimum: 0, maximum: 100 }, classification: "restricted", apiExposed: true }),
      field("taxTreatment", "string", {
        validation: { allowedValues: ["standard", "zero-rated", "exempt"] },
        classification: "confidential",
        aiReadable: true,
        apiExposed: true,
      }),
      field("reorderLevel", "integer", { validation: { minimum: 0, maximum: 1_000_000 }, aiReadable: true, apiExposed: true }),
      field("trackStock", "boolean", { aiReadable: true, apiExposed: true }),
      field("isActive", "boolean", { aiReadable: true, apiExposed: true }),
      field("createdAt", "datetime", { apiExposed: true }),
    ],
  },
  {
    name: "Employee",
    parent: "Company",
    domain: "people",
    searchable: false,
    aiVisible: false,
    auditEnabled: true,
    lifecycle: ["ACTIVE", "ENDED"],
    relationships: [
      relationship("company", "Company", "many-to-one"),
      relationship("createdBy", "User", "many-to-one"),
    ],
    fields: [
      field("id", "uuid", { unique: true, apiExposed: true }),
      field("tenantId", "uuid", { lookup: "Company" }),
      field("employeeNumber", "string", { required: true, unique: true, maxLength: 30, validation: { minLength: 1 }, classification: "confidential", apiExposed: true }),
      field("firstName", "string", { required: true, maxLength: 100, validation: { minLength: 1 }, classification: "restricted", apiExposed: true }),
      field("lastName", "string", { required: true, maxLength: 100, validation: { minLength: 1 }, classification: "restricted", apiExposed: true }),
      field("nationalId", "string", { maxLength: 50, classification: "restricted", apiExposed: true }),
      field("nssaNumber", "string", { maxLength: 50, classification: "restricted", apiExposed: true }),
      field("email", "string", { maxLength: 255, validation: email, classification: "restricted", apiExposed: true }),
      field("phone", "string", { maxLength: 50, classification: "restricted", apiExposed: true }),
      field("currency", "string", { required: true, validation: currencies, classification: "confidential", apiExposed: true }),
      field("basicSalary", "decimal", { required: true, validation: nonNegativeMoney, classification: "restricted", apiExposed: true }),
      field("status", "string", { validation: { allowedValues: ["ACTIVE", "ENDED"] }, classification: "confidential", apiExposed: true }),
      field("startDate", "date", { classification: "restricted", apiExposed: true }),
      field("endDate", "date", { classification: "restricted", apiExposed: true }),
      field("createdBy", "uuid", { lookup: "User" }),
      field("createdAt", "datetime", { apiExposed: true }),
      field("updatedAt", "datetime", { apiExposed: true }),
    ],
  },
  {
    name: "User",
    parent: "Company",
    domain: "identity",
    searchable: false,
    aiVisible: false,
    auditEnabled: true,
    lifecycle: ["active", "invited", "disabled"],
    relationships: [relationship("company", "Company", "many-to-one")],
    fields: [
      field("id", "uuid", { unique: true, apiExposed: true }),
      field("tenantId", "uuid", { lookup: "Company" }),
      field("email", "string", { required: true, unique: true, maxLength: 254, validation: email, classification: "restricted", apiExposed: true }),
      field("passwordHash", "string", { classification: "restricted" }),
      field("fullName", "string", { required: true, maxLength: 100, validation: { minLength: 2 }, classification: "restricted", apiExposed: true }),
      field("roleId", "uuid", { classification: "confidential", apiExposed: true }),
      field("isPlatformAdmin", "boolean"),
      field("platformRoleKey", "string", { maxLength: 100, classification: "confidential" }),
      field("status", "string", { validation: { allowedValues: ["active", "invited", "disabled"] }, apiExposed: true }),
      field("mustChangePassword", "boolean"),
      field("lastLoginAt", "datetime", { classification: "restricted" }),
      field("createdAt", "datetime", { apiExposed: true }),
    ],
  },
];
