export type EndpointAccess = "public" | "tenant" | "shared-authenticated" | "platform";
export type IsolationVector =
  | "public-contract"
  | "platform-denial"
  | "shared-projection"
  | "tenant-context"
  | "tenant-list-or-aggregate"
  | "tenant-object"
  | "tenant-object-mutation"
  | "tenant-create-or-action";

export type EndpointCoverage = {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  access: EndpointAccess;
  vector: IsolationVector;
  justification?: string;
};

// Maintained contract: the regression suite compares this manifest with the
// Express registrations and fails when an endpoint is added or removed.
export const endpointCoverageManifest: readonly EndpointCoverage[] = [
  { method: "GET", path: "/health", access: "public", vector: "public-contract", justification: "Operational liveness probe; returns no tenant data." },
  { method: "GET", path: "/healthz", access: "public", vector: "public-contract", justification: "Dependency-free liveness probe; returns version and process uptime only." },
  { method: "GET", path: "/readyz", access: "public", vector: "public-contract", justification: "Operational readiness probe; returns redacted check labels without tenant data or connection details." },
  { method: "GET", path: "/api/v1/healthz", access: "public", vector: "public-contract", justification: "Vercel-delivered alias of the dependency-free liveness probe." },
  { method: "GET", path: "/api/v1/readyz", access: "public", vector: "public-contract", justification: "Vercel-delivered alias of the redacted readiness probe." },
  { method: "POST", path: "/api/v1/auth/signup", access: "public", vector: "public-contract", justification: "Tenant bootstrap endpoint; no authenticated tenant exists yet." },
  { method: "POST", path: "/api/v1/auth/login", access: "public", vector: "public-contract", justification: "Credential exchange endpoint; rate-limited and intentionally unauthenticated." },
  { method: "POST", path: "/api/v1/auth/refresh", access: "public", vector: "public-contract", justification: "Refresh-token exchange endpoint; authenticates the rotating refresh token." },
  { method: "POST", path: "/api/v1/auth/password-reset/request", access: "public", vector: "public-contract", justification: "Password-reset initiation must be reachable before authentication." },
  { method: "POST", path: "/api/v1/auth/password-reset/complete", access: "public", vector: "public-contract", justification: "Password-reset completion authenticates a single-use reset token." },
  { method: "POST", path: "/api/v1/auth/mfa/verify-login", access: "public", vector: "public-contract", justification: "MFA challenge completion occurs before an application session is issued." },
  { method: "GET", path: "/api/v1/public/invoices/:token/pdf", access: "public", vector: "public-contract", justification: "Capability-token invoice view; access is governed by the unguessable share token." },
  { method: "GET", path: "/api/v1/public/workspaces/:subdomain/holding", access: "public", vector: "public-contract", justification: "Published holding page; intentionally public and limited to published branding." },
  { method: "POST", path: "/api/v1/public/payments/paynow/result", access: "public", vector: "public-contract", justification: "Payment-provider callback authenticated by provider payload verification." },
  { method: "GET", path: "/api/v1/me", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/search", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/metadata/objects", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/auth/change-password", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/auth/step-up", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/auth/logout", access: "tenant", vector: "tenant-create-or-action" },
  { method: "PATCH", path: "/api/v1/me/profile", access: "tenant", vector: "tenant-context" },
  { method: "GET", path: "/api/v1/auth/mfa", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/auth/mfa/enroll", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/auth/mfa/enroll/verify", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/auth/mfa/recovery-codes", access: "tenant", vector: "tenant-create-or-action" },
  { method: "DELETE", path: "/api/v1/auth/mfa", access: "tenant", vector: "tenant-context" },
  { method: "GET", path: "/api/v1/security/my-sessions", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/security/my-sessions/:id/revoke", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/notifications", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/security/activity", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/security/users", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/security/users/:id/:status", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/security/sessions/:id/revoke", access: "tenant", vector: "tenant-object-mutation" },
  { method: "PATCH", path: "/api/v1/profile", access: "tenant", vector: "tenant-context" },
  { method: "PATCH", path: "/api/v1/settings/branding", access: "tenant", vector: "tenant-context" },
  { method: "PATCH", path: "/api/v1/settings/holding-page", access: "tenant", vector: "tenant-context" },
  { method: "POST", path: "/api/v1/settings/logo", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/captures", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/captures/:id", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/captures/:id/review", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/captures", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/imports", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/imports/contacts/preview", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/imports/contacts/:id/commit", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/imports/products/preview", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/imports/products/:id/commit", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/imports/opening-stock/preview", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/imports/opening-stock/:id/commit", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/imports/bank-statement/preview", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/imports/bank-statement/:id/commit", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/bank-accounts", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/bank-accounts", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/bank-transactions", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/bank-accounts/:id/reconciliation-summary", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/bank-accounts/:id/reconciliation-worksheet", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/bank-accounts/:id/reconciliations", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/bank-accounts/:id/reconciliations", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/bank-reconciliations/:id/approve", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/bank-reconciliations/:id/report", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/bank-transactions/:id/match-candidates", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/bank-transactions/:id/match-invoice", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/bank-transactions/:id/split-candidates", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/bank-transactions/:id/post-bank-fee", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/bank-transactions/:id/transfer-candidates", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/bank-transactions/:id/match-transfer", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/bank-transactions/:id/match-invoices", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/contacts", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/invoice-customers", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/contacts", access: "tenant", vector: "tenant-create-or-action" },
  { method: "PATCH", path: "/api/v1/contacts/:id", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/contacts/bulk", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/contacts/deletions", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/contacts/deletion-requests", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/contacts/deletion-requests/:requestId/decision", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/contacts/:id/communication-preferences/email", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/contacts/:id/communication-preferences/email", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/contacts/:id/statements/send", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/contacts/:id", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/contacts/:id/timeline", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/suppliers", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/suppliers", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/suppliers/:id", access: "tenant", vector: "tenant-object" },
  { method: "PATCH", path: "/api/v1/suppliers/:id", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/deals", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/deals", access: "tenant", vector: "tenant-create-or-action" },
  { method: "PATCH", path: "/api/v1/deals/:id/stage", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/activities", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/products", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/products", access: "tenant", vector: "tenant-create-or-action" },
  { method: "PATCH", path: "/api/v1/products/:id/reorder-rule", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/warehouses", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/warehouses", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/settings/warehouses", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/settings/warehouses", access: "tenant", vector: "tenant-create-or-action" },
  { method: "PATCH", path: "/api/v1/settings/warehouses/:id", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/stock/adjust", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/stock/opening", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/stock/movements", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/purchase-requisitions", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/procurement/reference-data", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/purchase-requisitions", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/purchase-requisitions/:id/decision", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/request-for-quotes", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/request-for-quotes", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/request-for-quotes/:id/award", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/purchase-orders", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/purchase-orders", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/purchase-orders/:id/approve", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/purchase-orders/:id/receipts", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/goods-receipts", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/supplier-bills", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/supplier-bills/:id", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/supplier-bills/:id/match", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/reports/supplier-performance", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/supplier-bills", access: "tenant", vector: "tenant-create-or-action" },
  { method: "PUT", path: "/api/v1/supplier-bills/:id", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/supplier-bills/:id/post", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/accounts", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/exchange-rates", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/exchange-rates", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/invoices", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/invoices/:id", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/invoices/:id/pdf", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/invoices/:id/send", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/invoices/:id/payment-reminders/send", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/invoices/:id/share-links", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/invoices/:id/share-links", access: "tenant", vector: "tenant-object" },
  { method: "DELETE", path: "/api/v1/invoices/:id/share-links/:linkId", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/invoices", access: "tenant", vector: "tenant-create-or-action" },
  { method: "PATCH", path: "/api/v1/invoices/:id", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/invoices/:id/issue", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/invoices/:id/payments", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/invoices/:id/void", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/expenses", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/expenses", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/accounting/periods", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/accounting/periods/close", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/accounting/periods/:id/reopen", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/tasks", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/tasks", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/tasks/:id/close", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/settings/automation-rules", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "PUT", path: "/api/v1/settings/automation-rules/:key", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/documents/folders", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/documents/folders", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/documents", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/documents", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/documents/:id/versions", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/documents/:id/content", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/documents/:id/archive", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/documents/:id/restore", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/documents/:id", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/documents/approvals/list", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/documents/:id/approvals", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/documents/approvals/:approvalId/decide", access: "tenant", vector: "tenant-object-mutation" },
  { method: "PUT", path: "/api/v1/documents/:id/retention", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/blackbook/entries", access: "shared-authenticated", vector: "shared-projection", justification: "Curated country-pack directory is shared reference data." },
  { method: "GET", path: "/api/v1/blackbook/entries/:key", access: "shared-authenticated", vector: "shared-projection", justification: "Curated country-pack directory record is shared reference data." },
  { method: "GET", path: "/api/v1/verification/evidence", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/verification/evidence", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/verification/evidence/:id", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/verification/evidence/:id/renew", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/verification/evidence/:id/withdraw", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/network/profile", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "PUT", path: "/api/v1/network/profile", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/network/profile/publish", access: "tenant", vector: "tenant-create-or-action" },
  { method: "POST", path: "/api/v1/network/profile/unpublish", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/network/directory", access: "shared-authenticated", vector: "shared-projection", justification: "Explicitly published business profiles are visible across authenticated tenants." },
  { method: "GET", path: "/api/v1/network/directory/:id", access: "shared-authenticated", vector: "shared-projection", justification: "An explicitly published business profile is visible across authenticated tenants." },
  { method: "POST", path: "/api/v1/network/directory/:id/enquire", access: "shared-authenticated", vector: "shared-projection", justification: "Cross-tenant enquiry is an intentional network action; sender context remains tenant-derived." },
  { method: "GET", path: "/api/v1/network/enquiries", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/network/enquiries/:id/convert", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/network/enquiries/:id/dismiss", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/migration/projects", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/migration/projects", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/migration/projects/:id", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/migration/projects/:id/reconciliation", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/migration/projects/:id/steps/:kind/preview", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/migration/projects/:id/steps/:stepId/commit", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/migration/projects/:id/steps/:stepId/discard", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/migration/projects/:id/steps/:stepId/rollback", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/migration/projects/:id/sign-off", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/migration/projects/:id/close", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/settings/approval-policies", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "PUT", path: "/api/v1/settings/approval-policies/:subjectType", access: "tenant", vector: "tenant-object-mutation" },
  { method: "DELETE", path: "/api/v1/settings/approval-policies/:subjectType", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/payroll/config", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/payroll/employees", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/payroll/employees", access: "tenant", vector: "tenant-create-or-action" },
  { method: "PATCH", path: "/api/v1/payroll/employees/:id", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/payroll/runs", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/payroll/runs/:id", access: "tenant", vector: "tenant-object" },
  { method: "POST", path: "/api/v1/payroll/runs", access: "tenant", vector: "tenant-create-or-action" },
  { method: "PATCH", path: "/api/v1/payroll/runs/:id/payslips/:payslipId", access: "tenant", vector: "tenant-object-mutation" },
  { method: "DELETE", path: "/api/v1/payroll/runs/:id", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/payroll/runs/:id/post", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/payroll/runs/:id/reverse", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/journal", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/reports/snapshots", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/reports/snapshots", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/snapshots/:id", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/reports/snapshots/:id/pdf", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/reports/dashboard", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/trial-balance", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/profit-loss", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/balance-sheet", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/aged-receivables", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/inventory-valuation", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/vat", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/vat.csv", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/vat.pdf", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/statutory-pack", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/statutory-pack.csv", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/reports/statutory-pack.pdf", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/ai/read-models/business-summary", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/export/:entity", access: "tenant", vector: "tenant-object" },
  { method: "GET", path: "/api/v1/billing/subscription", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/billing/invoices", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "GET", path: "/api/v1/billing/payment-provider", access: "shared-authenticated", vector: "shared-projection", justification: "Payment-provider configuration is global non-secret reference data." },
  { method: "GET", path: "/api/v1/billing/payment-attempts", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/billing/invoices/:id/payment-attempts", access: "tenant", vector: "tenant-object-mutation" },
  { method: "POST", path: "/api/v1/billing/payment-attempts/:id/refresh", access: "tenant", vector: "tenant-object-mutation" },
  { method: "GET", path: "/api/v1/billing/plans", access: "shared-authenticated", vector: "shared-projection", justification: "Commercial plan catalogue is global reference data." },
  { method: "GET", path: "/api/v1/billing/arrears-status", access: "tenant", vector: "tenant-list-or-aggregate" },
  { method: "POST", path: "/api/v1/billing/upgrade-interest", access: "tenant", vector: "tenant-create-or-action" },
  { method: "GET", path: "/api/v1/platform/staff/roles", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/staff", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/staff", access: "platform", vector: "platform-denial" },
  { method: "PATCH", path: "/api/v1/platform/staff/:id", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/staff/:id/temporary-password", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/analytics", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/control-center", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/operations/email-failures/today", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/backup-manifests", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/backup-manifests", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/restore-drills", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/restore-drills", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/restore-drills/:id/review", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/referral-codes", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/referral-codes", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/referral-attributions", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/referral-attributions/:id/reviews", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/tenants", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/tenants/:id/features", access: "platform", vector: "platform-denial" },
  { method: "PUT", path: "/api/v1/platform/tenants/:id/features/:key", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/blackbook/import", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/blackbook/import-runs", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/billing/run", access: "platform", vector: "platform-denial" },
  { method: "POST", path: "/api/v1/platform/tenants/:id/mark-invoice-paid/:invoiceId", access: "platform", vector: "platform-denial" },
  { method: "GET", path: "/api/v1/platform/audit/:tenantId", access: "platform", vector: "platform-denial" },
];
